### ISSUE TITLE
Socket connection failed with latest LiveView version

### ISSUE THREAD

**Issue by Fudoshiki** [liveview-native/live_view_native#109]
live_view: **main**
liveview_native: **main**
live_view_native_swiftui: **main**

After this commit https://github.com/phoenixframework/phoenix_live_view/commit/84d07a633cabc1de2b83752b9c4aa75b2ca48136 socket connection is failing

```cmd
[error] GenServer #PID<0.1068.0> terminating
** (FunctionClauseError) no function clause matching in Plug.Conn.resp/3
    (plug 1.15.2) lib/plug/conn.ex:614: Plug.Conn.resp(%Plug.Conn{adapter: {Bandit.HTTP1.Adapter, :...}, assigns: %{native: %LiveViewNativePlatform.Env{custom_modifiers: [], default_layouts: %{root: "  <csrf-token value={get_csrf_token()} />\n  <NavigationStack>\n    <%= @inner_content %>\n  </NavigationStack>\n", app: "<%= @inner_content %>"}, eex_engine: Phoenix.LiveView.TagEngine, modifiers_struct: LiveViewNativePlatform.GenericModifiers, modifiers: %LiveViewNativePlatform.GenericModifiers{stack: []}, platform_config: %LiveViewNative.SwiftUI.Platform{app_name: nil, os_name: nil, os_version: nil, simulator_opts: nil, user_interface_idiom: nil, custom_modifiers: []}, platform_id: :swiftui, platform_modifiers: [], render_macro: :sigil_SWIFTUI, tag_handler: LiveViewNative.TagEngine, template_extension: ".swiftui.heex", template_namespace: LiveViewNative.SwiftUI, valid_targets: [:mac, :pad, :phone, :tv, :vision, :watch]}, os_version: nil, os: nil, format: :swiftui, target: nil, layout: false, app_version: nil, app_build: nil, bundle_id: nil, __changed__: %{native: true, os_version: true, os: true, format: true, target: true, app_version: true, app_build: true, bundle_id: true}, flash: %{}, content: {:safe, [60, "div", [" id=\"", "phx-F6PRsfIRQd95Ggyh", 34, " data", 45, "phx-main", " data", 45, "phx-session", 61, 34, "SFMyNTY.g2gDaAJhBXQAAAAIdwJpZG0AAAAUcGh4LUY2UFJzZklSUWQ5NUdneWh3B3Nlc3Npb250AAAAAHcEdmlld3cWRWxpeGlyLk1pYVdlYi5Ib21lTGl2ZXcKcGFyZW50X3BpZHcDbmlsdwlyb290X3ZpZXd3FkVsaXhpci5NaWFXZWIuSG9tZUxpdmV3CHJvb3RfcGlkdwNuaWx3BnJvdXRlcncURWxpeGlyLk1pYVdlYi5Sb3V0ZXJ3DGxpdmVfc2Vzc2lvbmgCdwdkZWZhdWx0bggAo6yKlpvRoxduBgBFNa2cjAFiAAFRgA.AJ5qjb7qOP2Eo-SHYgEZ42rsfKWK12AXVF-LBVSfwLY", 34, " data", 45, "phx-static", 61, 34, "SFMyNTY.g2gDaAJhBXQAAAADdwJpZG0AAAAUcGh4LUY2UFJzZklSUWQ5NUdneWh3CmFzc2lnbl9uZXdqdwVmbGFzaHQAAAAAbgYARTWtnIwBYgABUYA.ub29nukwwCyU1il71cbutGpuqt3P3f7TBI2mAQnfU_I", 34], 62, ["<compiled-lvn-stylesheet", " body=\"%{}\"", ">", ["<VStack id=\"hello-native\">\n  <Text>\n    Hello native!\n  </Text>\n</VStack>"], "\n\n<iframe src=\"/phoenix/live_reload/frame\"></iframe>\n</compiled-lvn-stylesheet>"], 60, 47, "div", 62]}, live_action: nil, live_module: TestAppWeb.HomeLive}, body_params: %{}, cookies: %{}, halted: false, host: "localhost", method: "GET", owner: #PID<0.1068.0>, params: %{"_lvn" => %{"format" => "swiftui"}}, path_info: [], path_params: %{}, port: 4000, private: %{:phoenix_live_view => {TestAppWeb.HomeLive, [action: nil, router: TestAppWeb.Router], %{extra: %{on_mount: [%{function: &TestAppWeb.RenderNative.on_mount/4, id: {TestAppWeb.RenderNative, :default}, stage: :mount}]}, name: :default, vsn: 1703435550251986083}}, :phoenix_template => "template.swiftui", :phoenix_view => %{_: Phoenix.LiveView.Static}, :phoenix_format => "swiftui", :phoenix_root_layout => %{"html" => {TestAppWeb.Layouts, :root_swiftui}}, :phoenix_endpoint => TestAppWeb.Endpoint, :plug_session_fetch => :done, :plug_session => %{}, :before_send => [#Function<1.25792984/1 in LiveViewNative.SessionPlug.before_send_inject_reloader/3>, #Function<0.71811376/1 in Plug.CSRFProtection.call/2>, #Function<4.6073741/1 in Phoenix.Controller.fetch_flash/2>, #Function<0.76384852/1 in Plug.Session.before_send/2>, #Function<1.492364/1 in Phoenix.LiveReloader.before_send_inject_reloader/3>], TestAppWeb.Router => [], :phoenix_router => TestAppWeb.Router, :phoenix_layout => %{_: false}}, query_params: %{"_lvn" => %{"format" => "swiftui"}}, query_string: "_lvn%5Bformat%5D=swiftui", remote_ip: {127, 0, 0, 1}, req_cookies: %{}, req_headers: [{"user-agent", "TestApp/1.0 CFNetwork/1490.0.4 Darwin/23.3.0"}, {"accept-encoding", "gzip, deflate"}, {"connection", "keep-alive"}, {"accept-language", "ru"}, {"accept", "*/*"}, {"host", "localhost:4000"}], request_path: "//", resp_body: nil, resp_cookies: %{}, resp_headers: [{"content-type", "application/octet-stream; charset=utf-8"}, {"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "F6PRsfIGYTxOeRoAAAyB"}, {"referrer-policy", "strict-origin-when-cross-origin"}, {"x-content-type-options", "nosniff"}, {"x-download-options", "noopen"}, {"x-frame-options", "SAMEORIGIN"}, {"x-permitted-cross-domain-policies", "none"}, {"content-security-policy", "default-src 'self'"}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: nil}, 200, {:safe, [60, "div", [" id=\"", "phx-F6PRsfIRQd95Ggyh", 34, " data", 45, "phx-main", " data", 45, "phx-session", 61, 34, "SFMyNTY.g2gDaAJhBXQAAAAIdwJpZG0AAAAUcGh4LUY2UFJzZklSUWQ5NUdneWh3B3Nlc3Npb250AAAAAHcEdmlld3cWRWxpeGlyLk1pYVdlYi5Ib21lTGl2ZXcKcGFyZW50X3BpZHcDbmlsdwlyb290X3ZpZXd3FkVsaXhpci5NaWFXZWIuSG9tZUxpdmV3CHJvb3RfcGlkdwNuaWx3BnJvdXRlcncURWxpeGlyLk1pYVdlYi5Sb3V0ZXJ3DGxpdmVfc2Vzc2lvbmgCdwdkZWZhdWx0bggAo6yKlpvRoxduBgBFNa2cjAFiAAFRgA.AJ5qjb7qOP2Eo-SHYgEZ42rsfKWK12AXVF-LBVSfwLY", 34, " data", 45, "phx-static", 61, 34, "SFMyNTY.g2gDaAJhBXQAAAADdwJpZG0AAAAUcGh4LUY2UFJzZklSUWQ5NUdneWh3CmFzc2lnbl9uZXdqdwVmbGFzaHQAAAAAbgYARTWtnIwBYgABUYA.ub29nukwwCyU1il71cbutGpuqt3P3f7TBI2mAQnfU_I", 34], 62, ["<compiled-lvn-stylesheet", " body=\"%{}\"", ">", ["<VStack id=\"hello-native\">\n  <Text>\n    Hello native!\n  </Text>\n</VStack>"], "\n\n<iframe src=\"/phoenix/live_reload/frame\"></iframe>\n</compiled-lvn-stylesheet>"], 60, 47, "div", 62]})
    (plug 1.15.2) lib/plug/conn.ex:593: Plug.Conn.send_resp/3
    (phoenix 1.7.10) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
    (test_app 0.1.0) lib/test_app_web/endpoint.ex:1: TestAppWeb.Endpoint.plug_builder_call/2
    (test_app 0.1.0) deps/plug/lib/plug/debugger.ex:136: TestAppWeb.Endpoint."call (overridable 3)"/2
    (test_app 0.1.0) lib/test_app_web/endpoint.ex:1: TestAppWeb.Endpoint.call/2
    (phoenix 1.7.10) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (bandit 1.1.2) lib/bandit/pipeline.ex:101: Bandit.Pipeline.call_plug/2
    (bandit 1.1.2) lib/bandit/pipeline.ex:22: Bandit.Pipeline.run/6
    (bandit 1.1.2) lib/bandit/http1/handler.ex:31: Bandit.HTTP1.Handler.handle_data/3
    (bandit 1.1.2) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
    (bandit 1.1.2) /Users/Fudoshiki/Code/TestApp/deps/thousand_island/lib/thousand_island/handler.ex:399: Bandit.DelegatingHandler.handle_continue/2
    (stdlib 5.2) gen_server.erl:1085: :gen_server.try_handle_continue/3
    (stdlib 5.2) gen_server.erl:995: :gen_server.loop/7
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:continue, :handle_connection}
State: {%ThousandIsland.Socket{socket: #Port<0.37>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, silent_terminate_on_error: false, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.4251886271.1122500609.174431>, start_time: -576460655198589677, start_metadata: %{telemetry_span_context: #Reference<0.4251886271.1122500609.174431>, remote_port: 52937, remote_address: {127, 0, 0, 1}, parent_telemetry_span_context: #Reference<0.4251886271.1122500613.172191>}}}, %{opts: %{websocket: [], http_1: [], http_2: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {TestAppWeb.Endpoint, []}}, handler_module: Bandit.InitialHandler, http_1_enabled: true, http_2_enabled: true, websocket_enabled: true}}
```

Comment out the line https://github.com/liveview-native/live_view_native/blob/main/lib/live_view_native/session_plug.ex#L20 is solve it

```cmd
[info] CONNECTED TO Phoenix.LiveView.Socket in 25µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "FA8GAC11Mx4GHyc4E310fW8qEQs9CjU5xbcNb4rtGnAWUIL-0eVOlgQR", "vsn" => "2.0.0"}
[debug] MOUNT TestAppWeb.HomeLive
  Parameters: %{}
  Session: %{"_csrf_token" => "lmeNOAAjAqfoF48P_OGDQmdk"}
[debug] Replied in 29ms
```

**Comment by bcardarella** [comment]
@Fudoshiki can you confirm if you have `phoenix_live_view` v0.20.3 installed? If so then this is related to that specific version. In that version of LiveView this commit is included: https://github.com/phoenixframework/phoenix_live_view/commit/84d07a633cabc1de2b83752b9c4aa75b2ca48136
which changes the response type of the body from `html` always to use what the `format` is set to for static renders (dead render). This means the body of the response isnt'b being formatted encoded and this specific problem can be fixed with adding the following to your app config:

```elixir
config :mime, :types, %{
  "text/swiftui" => ["swiftui"]
}

config :phoenix_template, :format_encoders,
  swiftui: Phoenix.HTML.Engine
```

however, you will run into other problems as the layouts also broke with v0.20.3. I am going to release a v0.2.0-rc.1 today that will version lock `phoenix_live_view` to `< 0.20.3` which fixes the problem. The `v0.3.0` version of LiveView Native is being refactored around these upstream changes in LiveView so it'll be OK.

You can alternatively version lock LiveView yourself
