### ISSUE TITLE
`__live__` is undefined or private

### ISSUE THREAD

**Issue by carson-katri** [liveview-native/live_view_native#114]
The following error occurs intermittently on the web:

```
[error] #PID<0.946.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.690.0>, stream id 8) terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function LvnDemo3Web.HomeLive.__live__/0 is undefined or private
        (lvn_demo3 0.1.0) LvnDemo3Web.HomeLive.__live__()
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/static.ex:260: Phoenix.LiveView.Static.load_live!/2
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/static.ex:88: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.10) lib/phoenix/router.ex:432: Phoenix.Router.__call__/5
        (lvn_demo3 0.1.0) lib/lvn_demo3_web/endpoint.ex:1: LvnDemo3Web.Endpoint.plug_builder_call/2
        (lvn_demo3 0.1.0) deps/plug/lib/plug/debugger.ex:136: LvnDemo3Web.Endpoint."call (overridable 3)"/2
        (lvn_demo3 0.1.0) lib/lvn_demo3_web/endpoint.ex:1: LvnDemo3Web.Endpoint.call/2
        (phoenix 1.7.10) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.10.0) /Users/carson.katri/Documents/LiveViewNative/TestProjects/lvn_demo3/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /Users/carson.katri/Documents/LiveViewNative/TestProjects/lvn_demo3/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) /Users/carson.katri/Documents/LiveViewNative/TestProjects/lvn_demo3/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by bcardarella** [comment]
Fixed in https://github.com/liveview-native/live_view_native/commit/1891980dcc8063fce7fb7f71116cd3be51911b1f
