### ISSUE TITLE
templates don't allow for id to be a non-string value

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/live_view_native#131]
Example:

```heex
<HStack :for={landmark <- @landmarks} id={landmark["id"]}>
```

Result:

```
** (ArgumentError) attempting to set id attribute to 1001, but setting the DOM ID to a number can lead to unpredictable behaviour. Instead consider prefixing the id with a string, such as "user-1001" or similar
        (phoenix_html 3.3.3) lib/phoenix_html.ex:285: Phoenix.HTML.id_value/1
        (phoenix_html 3.3.3) lib/phoenix_html.ex:250: Phoenix.HTML.build_attrs/1
        (phoenix_html 3.3.3) lib/phoenix_html.ex:218: Phoenix.HTML.attributes_escape/1
        (lvn_workshop 0.1.0) lib/lvn_workshop_web/live/swiftui/home_live.swiftui.neex:2: anonymous fn/1 in LvnWorkshopWeb.HomeLive.SwiftUI.render/2
        (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
        (lvn_workshop 0.1.0) lib/lvn_workshop_web/live/swiftui/home_live.swiftui.neex:1: anonymous fn/2 in LvnWorkshopWeb.HomeLive.SwiftUI.render/2
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:391: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:544: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:389: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/diff.ex:136: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/static.ex:249: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/static.ex:132: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.20.3) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.11) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
        (lvn_workshop 0.1.0) lib/lvn_workshop_web/endpoint.ex:1: LvnWorkshopWeb.Endpoint.plug_builder_call/2
        (lvn_workshop 0.1.0) deps/plug/lib/plug/debugger.ex:136: LvnWorkshopWeb.Endpoint."call (overridable 3)"/2
        (lvn_workshop 0.1.0) lib/lvn_workshop_web/endpoint.ex:1: LvnWorkshopWeb.Endpoint.call/2
        (phoenix 1.7.11) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.7.0) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
```

**Comment by bcardarella** [comment]
Closed by https://github.com/liveview-native/live_view_native/pull/132
