### ISSUE TITLE
error when running mix lvn.install

### ISSUE THREAD

**Issue by mayel** [liveview-native/live_view_native#48]
OS: Mac 13.5.2 
Arch: ARM
Elixir install: 1.15 via [rtx](https://github.com/jdx/rtx)

Output:
```
* configuring live_view_native_swift_ui
** (ArgumentError) all arguments for System.cmd/3 must be binaries
    (elixir 1.15.5) lib/system.ex:1083: System.cmd/3
    (live_view_native 0.1.0) lib/mix/tasks/install.ex:56: anonymous fn/4 in Mix.Tasks.Lvn.Install.run/1
    (elixir 1.15.5) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (live_view_native 0.1.0) lib/mix/tasks/install.ex:47: Mix.Tasks.Lvn.Install.run/1
    (mix 1.15.5) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.5) lib/mix/cli.ex:92: Mix.CLI.run_task/2
    /Users/me/.local/share/rtx/installs/elixir/1.15.5-otp-26/bin/mix:2: (file)
```

**Comment by mayel** [comment]
FYI running `System.cmd("elixir", ["-v"])` in iex does work as expected:
```{"Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]\n\nElixir 1.15.5 (compiled with Erlang/OTP 26)\n", 0}

**Comment by mayel** [comment]
I've identified the issue, our `mix.exs` contains lines line `Code.eval_file("extra_code.exs")` at the top before `defmodule` which `infer_app_name` doesn't expect.

**Comment by supernintendo** [comment]
Nice catch @mayel, fixed in https://github.com/liveview-native/live_view_native/pull/54.
